// <auto-generated />
using System;
using ExperementsAPI.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExperementsAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240218110643_ExperimentDB")]
    partial class ExperimentDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExperementsAPI.Model.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ExperementsAPI.Model.DeviceExperiments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDevice")
                        .HasColumnType("int");

                    b.Property<int>("IdExperimentValue")
                        .HasColumnType("int");

                    b.Property<int?>("IdExperimentValues")
                        .HasColumnType("int");

                    b.Property<int>("IdExperiments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDevice");

                    b.HasIndex("IdExperimentValues");

                    b.HasIndex("IdExperiments");

                    b.ToTable("DeviceExperiments");
                });

            modelBuilder.Entity("ExperementsAPI.Model.ExperimentValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdExperiments")
                        .HasColumnType("int");

                    b.Property<double?>("ProcentValue")
                        .HasColumnType("float");

                    b.Property<string>("Values")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdExperiments");

                    b.ToTable("ExperimentValues");
                });

            modelBuilder.Entity("ExperementsAPI.Model.Experiments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExperimentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("ExperementsAPI.Model.DeviceExperiments", b =>
                {
                    b.HasOne("ExperementsAPI.Model.Device", "Device")
                        .WithMany("DeviceExperiments")
                        .HasForeignKey("IdDevice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExperementsAPI.Model.ExperimentValues", "ExperimentValues")
                        .WithMany("DeviceExperiments")
                        .HasForeignKey("IdExperimentValues");

                    b.HasOne("ExperementsAPI.Model.Experiments", "Experiments")
                        .WithMany("DeviceExperiments")
                        .HasForeignKey("IdExperiments")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("ExperimentValues");

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("ExperementsAPI.Model.ExperimentValues", b =>
                {
                    b.HasOne("ExperementsAPI.Model.Experiments", "Experiments")
                        .WithMany("ExperimentValues")
                        .HasForeignKey("IdExperiments")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("ExperementsAPI.Model.Device", b =>
                {
                    b.Navigation("DeviceExperiments");
                });

            modelBuilder.Entity("ExperementsAPI.Model.ExperimentValues", b =>
                {
                    b.Navigation("DeviceExperiments");
                });

            modelBuilder.Entity("ExperementsAPI.Model.Experiments", b =>
                {
                    b.Navigation("DeviceExperiments");

                    b.Navigation("ExperimentValues");
                });
#pragma warning restore 612, 618
        }
    }
}
